name       : xdotool
version    : 3.20160805.1
release    : 3
source     :
    - https://github.com/jordansissel/xdotool/archive/v3.20160805.1.tar.gz : ddafca1239075c203769c17a5a184587731e56fbe0438c09d08f8af1704e117a
license    : BSD-2-Clause
component  : system.utils
summary    : Fake input from the mouse and keyboard very easily
description: |
    Fake input from the mouse and keyboard very easily
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
