name       : xdotool
version    : 3.20210903.1
release    : 4
source     :
    - https://github.com/jordansissel/xdotool/archive/v3.20210903.1.tar.gz : da1fa50853cf1f83765f3bb17cf97bcbb76e763483ca499c1940c3401d45c894
license    : BSD-2-Clause
component  : system.utils
summary    : Fake input from the mouse and keyboard very easily
description: |
    Fake input from the mouse and keyboard very easily
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr INSTALLMAN=/usr/share/man
